services:
  redis:
    image: "redis/redis-stack-server"
    ports:
      - 6379:6379
    #environment:
      #REDIS_ARGS: "--requirepass root"

  #neo4j:
   # image: neo4j:latest
   # ports:
    #  - "7474:7474"
     # - "7687:7687"
    #environment:
    #  - NEO4J_AUTH=neo4j/brahmsian
     # - NEO4J_PLUGINS=["apoc"]

  ollama:
    image: "ollama/ollama"
    container_name: ollama
    profiles:
      - ollama
    ports:
      - 11434
    volumes:
      - ~/.ollama/models:/root/.ollama/models
  ollama-runner:
    container_name: ollama-runner
    profiles:
      - ollama
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    command: docker exec ollama ollama run llama3
    depends_on:
      - ollama