spring:
  autoconfigure.exclude: |
    org.springframework.ai.autoconfigure.azure.openai.AzureOpenAiAutoConfiguration,
    org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration
  ai.openai:
    chat:
      options.model: gpt-4o
      options.temperature: 1.0
    image.options:
      model: dall-e-3
<<<<<<< HEAD
      size: 1024x1024
    #api-key: "YOUR_API_KEY"
    #configuration for a vllm privately hosted 
    #base-url: "http://vllm.vllm.svc.cluster.local:8000"
=======
    api-key:
>>>>>>> parent of 4753e82 (doc)
